---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api
  namespace: cloudflare-tunnel-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare-api
    template:
      data:
        account_id: "{{ .account_id }}"
        api_token: "{{ .api_token }}"
        tunnel_name: "${cluster_name}"
  data:
    - secretKey: account_id
      remoteRef:
        key: CLOUDFLARE_ACCOUNT_ID
    - secretKey: api_token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
