---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kyverno
      version: "3.8.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno-system
      interval: 10m
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    admissionController:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 384Mi
    backgroundController:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    cleanupController:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    reportsController:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
